# Get user by ID
GET http://localhost:3333/api/blog-user/65b4ccafd46fa5d9ba8d201c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI0Y2NhZmQ0NmZhNWQ5YmE4ZDIwMWMiLCJlbWFpbCI6InVzZXIwMDFAbG9jYWwubG9jYWwiLCJmaXJzdG5hbWUiOiJVc2VyMDAxIiwibGFzdG5hbWUiOiJTbWl0aDAwMSIsImlhdCI6MTcwNjM0NzY5NywiZXhwIjoxNzA2MzQ4NTk3fQ.U3YvB2IwJC-HWRg5C-xxZf3kzisBPB5Xy6qo4KUGMzU