
# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user001@local.local",
  "firstname": "User001",
  "lastname": "Smith001",
  "newPassword": "123456"
}

###


# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user001@local.local",
  "password": "123456"
}

###


# Refresh JWT
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI3NzZiOTRlYzM0YjBhNTE0MWE5YTMiLCJlbWFpbCI6InVzZXIwMDFAbG9jYWwubG9jYWwiLCJmaXJzdG5hbWUiOiJVc2VyMDAxIiwibGFzdG5hbWUiOiJTbWl0aDAwMSIsImlhdCI6MTcwNjUyMjMwMSwiZXhwIjoxNzA2Njk1MTAxfQ.rDl25biB0L6xW7UwMA6bFyBGI3vMIM_Tg5WVt-39C-Q

###


# Change user password
POST http://localhost:3001/api/auth/changepwd HTTP/1.1
Content-Type: application/json

{
  "email": "user002@local.local",
  "password": "123456",
  "newPassword": "654321"
}

###

# Login user. New password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user001@local.local",
  "password": "654321"
}

###