version: '3.9'
services:
  user.mongo.db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: user
    ports:
      - 27017:27017
    volumes:
      - mongo.user:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-account --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  user.mongo.ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpass@user.mongo.db:27017/

volumes:
  mongo.user:
